### ISSUE TITLE
Handbrake .dmg issue

### ISSUE THREAD

**Issue by eshirk** [autopkg/keeleysam-recipes#102]
Handbrake.munki.recipe is failing with this error: "ERROR: hdiutil error hdiutil: imageinfo failed - image not recognized".

Running hdiutil imageinfo against a direct download gives good results. something up with the Sparkle feed, maybe?

**Comment by flammable** [comment]
I was just troubleshooting the same thing. If you open the unrecognized DMG in a text editor, you'll see it's actually downloaded an error page.

I ended up switching to the .munki version of this recipe, which works well:

https://github.com/autopkg/recipes/tree/master/Handbrake

**Comment by eshirk** [comment]
Thanks, Mike! Didn't see this one, but it does indeed work well. I'll go ahead and close this issue.
