### ISSUE TITLE
Opera Download Failed

### ISSUE THREAD

**Issue by beatlemike** [autopkg/keeleysam-recipes#103]
Error running recips, "Can't read http://get.geo.opera.com/ftp/pub/opera/desktop/60.0.3255.84/mac/: HTTP Error 404: Not Found"

Opera.download.recipe

There is no Opera for Mac 60.0.3255.84, it's a windows only build. So the Download keeps failing.

**Comment by macmule** [comment]
@beatlemike the following seem to work: https://github.com/autopkg/bochoven-recipes

**Comment by macmule** [comment]
Also see: https://github.com/autopkg/keeleysam-recipes/issues/66 & https://github.com/autopkg/keeleysam-recipes/issues/70

**Comment by beatlemike** [comment]
Does that mean this recipe is no longer maintained?
