### ISSUE TITLE
FileZilla.munki recipe failing with bad URL

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/keeleysam-recipes#104]
Hey folks,

Looks like the FileZilla recipe is failing. I'm not sure how related this is to the older issues and merge requests but it looks like the processor isn't returning a valid URL:

```
FileZillaURLProvider
{'Input': {'product_name': u'FileZilla'}}
FileZillaURLProvider: Found URL FileZilla
{'Output': {'url': 'FileZilla', 'version': '-'}}
URLDownloader
{'Input': {'CHECK_FILESIZE_ONLY': True,
           'filename': u'FileZilla.tar.bz2',
           'request_headers': {
    "user-agent" = "FileZilla 3.25.1";
},
           'url': 'FileZilla'}}
URLDownloader: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
Curl failure: Could not resolve host: FileZilla (exit code 6)
Failed.

The following recipes failed:
    local.munki.FileZilla-dataJAR
        Error in local.munki.FileZilla-dataJAR: Processor: URLDownloader: Error: Curl failure: Could not resolve host: FileZilla (exit code 6)

```

**Comment by n8felton** [comment]
I believe this is because they have a bad cert right now.

Issue opened at https://trac.filezilla-project.org/ticket/11934#ticket

**Comment by Daz-wallace** [comment]
Looks like the comments aren't great on that thread?

**Comment by dcoobs** [comment]
Perhaps we switch to using [https://filezilla-project.org/download.php?show_all=1](https://filezilla-project.org/download.php?show_all=1)?

It looks like [https://filezilla-project.org/download.php?platform=osx](https://filezilla-project.org/download.php?platform=osx) is the [sponsored setup](https://filezilla-project.org/sponsored_updates.php) which I'm not a fan of.

**Comment by macmule** [comment]
Bump?

**Comment by roosteng** [comment]
The trouble appears to be missing intermediate certificates:

https://trac.filezilla-project.org/ticket/11934
https://trac.filezilla-project.org/ticket/11941

**Comment by dcoobs** [comment]
The developer has made it pretty clear that he's not going to change the way he's doing things so all we can do is adapt

**Comment by grahampugh** [comment]
It seems ok using the link embedded in https://filezilla-project.org/download.php?show_all=1

At present this is `https://dl1.cdn.filezilla-project.org/client/FileZilla_3.42.1_macosx-x86.app.tar.bz2?h=8ynLguq8MP3G1t8mRKtpWA&x=1560962154`

**Comment by fuzzylogiq** [comment]
Does that have bloatware bundled though?

**Comment by grahampugh** [comment]
@fuzzylogiq I don’t think so. I think it’s only the installer that’s bloated.

**Comment by dcoobs** [comment]
The link on [https://filezilla-project.org/download.php?platform=osx](https://filezilla-project.org/download.php?platform=osx) is a small file (1.7 MB) that is an app that runs and installs the actual application (FWIW, our A/V product wouldn't even let me launch the installer).

The link on [https://filezilla-project.org/download.php?show_all=1](https://filezilla-project.org/download.php?show_all=1) is a tar file that contains the entire application (~37 MB).

**Comment by n8felton** [comment]
Just to note this somewhere, the updated url appears to be something like 
```
https://update.filezilla-project.org/update.php?osversion=10.14&platform=x86_64-apple-darwin18.6.0&version=3.43.0
```

With that, trying to load it with this command doesn't return anything useful.
```
curl -A "FileZilla/3.43.0" -kL "https://update.filezilla-project.org/update.php?osversion=10.14&platform=x86_64-apple-darwin18.6.0&version=3.43.0"
```

I'm going to take a whack at just removing the FileZillaURLProvider Processor and instead scrape https://filezilla-project.org/download.php?show_all=1 for the file.
