### ISSUE TITLE
FileZilla download failing

### ISSUE THREAD

**Issue by eshirk** [autopkg/keeleysam-recipes#142]
I *think* the download URL may have changed, but the regex is eluding me.  The current download URL is: 

https://dl2.cdn.filezilla-project.org/client/FileZilla_3.58.0_macosx-x86.tar.bz2?h=B3vS3yBN3FjpFmGhmPZm_A&x=1644876098

**Comment by ResidentChief** [comment]
Howdy - just had this come up in the MacAdmins slack.  I think this is the code that needs updating

`<key>RE_PATTERN</key>
		<string>&lt;a href=\"(?P&lt;url&gt;http[s]?.*?(?P&lt;filename&gt;FileZilla_(?P&lt;version&gt;[\d.]+)_macosx-x86.*?\.app\.tar\.bz2).*?)\"</string>`

**Comment by ResidentChief** [comment]
Someone just bought this up in MacAdmins slack, the code to fix it required adding the -x86 at the end of the file name, and removing the .app from the extension

`<key>RE_PATTERN</key>
<string>&lt;a href=\"(?P&lt;url&gt;http[s]?.*?(?P&lt;filename&gt;FileZilla_(?P&lt;version&gt;[\d.]+)_macosx-x86.*?\.tar\.bz2).*?)\"</string> `

**Comment by floriangeyer** [comment]
I’m getting this error. Anyone else?

`Error in local.munki.FileZilla: Processor: URLTextSearcher: Error: No match found on URL: https://filezilla-project.org/download.php?show_all=1`

**Comment by fmiskic** [comment]
> I’m getting this error. Anyone else?
> 
> `Error in local.munki.FileZilla: Processor: URLTextSearcher: Error: No match found on URL: https://filezilla-project.org/download.php?show_all=1`

The fix is posted by @ResidentChief 

Any update when the regex will get patched publicly? 

Thanks!

**Comment by homebysix** [comment]
Should have been resolved by [this](https://github.com/autopkg/keeleysam-recipes/commit/67507d64297c9a8659f8fe21a5274c46fa0a1c55). Closing.
