### ISSUE TITLE
Duo Device Health.download.recipe isn't downloading new version

### ISSUE THREAD

**Issue by bolaussen** [autopkg/keeleysam-recipes#151]
Duo Device Health 3.2.0.0 was released yesterday and the download recipe is still grabbing 3.1.0.0

**Comment by arubdesu** [comment]
Yup, as of 3.0 they're using a json-based feed and have abandoned the sparkle xml version because unannounced reasons. Working on a fix

**Comment by bolaussen** [comment]
Hey @arubdesu thanks for working on this. I just tried running my override file and got the following error:
`Processor: PkgCopier: Error: list index out of range`

Did the .pkg recipe work for you after the change you made to the download recipe?

**Comment by vao-brex** [comment]
I can confirm that this is an issue for me  as well. Seemingly a variable is missing:

`Use of undefined key in variable substitution: 'version'`

**Comment by arubdesu** [comment]
Pardon the partial fix, munki users don't have to mess about with as many steps as other recipes require ¯\_(ツ)_/¯ but I shouldn't have left it half-broken for what people actually use.
However some changes make sense to me... you no longer need a pkg recipe, the download recipe now results in a pkg (previously renamed from "Install-DuoDeviceHealth" in a dmg) with the version appended at the source. If you use e.g. a Jamf recipe and must distinctly name the artifact you throw in its clumsy storage, at its most basic this has you covered. I'm still going to set the var in the env in a new commit I'm working on, but I cannot confirm it works. A Jamf recipe would also want to point at the download recipe as the 'parent', but that's not in this repo so I can't assist with that.

**Comment by vao-brex** [comment]
Thanks for the explanation @arubdesu

**Comment by arubdesu** [comment]
@bolaussen you may want to try reaching out to @keeleysam (`@samuel`) in the #autopkg public channel on MacAdmins Slack if you want to remind him about this, when he merges it my override will require an update so I'm in no rush to bother him 😜
