### ISSUE TITLE
Handbrake Munki recipe downloads DMG but fails to mount

### ISSUE THREAD

**Issue by cairnsmaterio** [autopkg/keeleysam-recipes#25]
NB: New to GitHub, bear with me while I get my head around it. :)

Here's an install failure output when I tried adding Handbrake to our in-house Munki repo.

The following recipes failed:
Handbrake.munki

Error in com.github.autopkg.munki.Handbrake: Processor: MunkiImporter: Error: creating pkginfo for /Users/riordanw/Library/AutoPkg/Cache/com.github.autopkg.munki.Handbrake/downloads/Handbrake.dmg failed:

WARNING: /Users/riordanw/Library/AutoPkg/Cache/com.github.autopkg.munki.Handbrake/downloads/Handbrake.dmg is a writable disk image. Checksum verification is not supported.

WARNING: Consider converting /Users/riordanw/Library/AutoPkg/Cache/com.github.autopkg.munki.Handbrake/downloads/Handbrake.dmg to a read-only disk image.

ERROR: Error: "hdiutil: attach failed - no mountable file systems" while mounting Handbrake.dmg.
Could not mount /Users/riordanw/Library/AutoPkg/Cache/com.github.autopkg.munki.Handbrake/downloads/Handbrake.dmg!

Workaround: Running hdiutil convert /path/to/file.dmg -o UDRO /path/to/file.dmg and then running the Munki recipe again successfully imports.

Looks to be the the Handbrake DMG is writable and needs to be converted to read-only, is there a mechanism in AutoPkg that we can use as a pre-flight operation before the DMG is mounted?

**Comment by gregneagle** [comment]
Have you tried opening /Users/riordanw/Library/AutoPkg/Cache/com.github.autopkg.munki.Handbrake/downloads/Handbrake.dmg in the Finder?

**Comment by cairnsmaterio** [comment]
The DMG doesn't open in Finder, reason being no mountable file systems.

    cd ~/Library/AutoPkg/Cache/com.github.autopkg.munki.Handbrake/downloads/

After changing into the downloads directory this was the workaround I used:

    mv Handbrake.dmg HandbrakeRW.dmg
    hdiutil convert HandbrakeRW.dmg -o UDRO Handbrake.dmg

Running autopkg run -v Handbrake.munki completed successfully and imported the image into my Munki repo.

**Comment by gregneagle** [comment]
That doesn't make much sense. Whether or not the dmg is read-write and whether or not the dmg has any mountable filesystems are two different things. One does not affect the other.

**Comment by cairnsmaterio** [comment]
Okay so I've cleared out the downloads directory and run autopkg run -v Handbrake.munki again, we'll see what happens with the output. It's still downloading the file at the moment (should have been done already) so I'll report back. Hoping this is just a transient issue but thought I'd document all the same.

I tested with the Handbrake.download recipe just to see if it was something transient with the DMG that's provided at that download URL but it mounted just fine.

**Comment by cairnsmaterio** [comment]
Okay downloaded the file again from the Munki recipe, same message. Can't open the DMG in Finder either.

**Comment by gregneagle** [comment]
Works fine here:

```
% autopkg run Handbrake.munki
Processing Handbrake.munki...

The following new items were imported into Munki:
    Name       Version        Catalogs  Pkginfo Path                                  Pkg Repo Path                               
    ----       -------        --------  ------------                                  -------------                               
    HandBrake  0.10.1 x86_64  testing   apps/HandBrake/HandBrake-0.10.1 x86_64.plist  apps/HandBrake/HandBrake-0.10.1 x86_64.dmg  

The following new items were downloaded:
    Download Path                                                                                              
    -------------                                                                                              
    /Users/gneagle/Library/AutoPkg/Cache/com.github.keeleysam.autopkg.munki.HandBrake/downloads/HandBrake.dmg 
```

**Comment by cairnsmaterio** [comment]
What version of OS X are you running? Could be something Yosemite-specific as I've run this recipe a few times and am getting the same result each time.

**Comment by keeleysam** [comment]
I think you must be hitting a bad mirror.  This is not an issue with the recipe itself, I would imagine you'd have the same issue using Handbrake's built-in Sparkle updater.  It downloads from this URL http://handbrake.fr/rotation.php?file=HandBrake-0.10.1-MacOSX.6_GUI_x86_64.dmg&update=true

I am on 10.10.2 and it works just fine.
```
autopkg run Handbrake.munki
Processing Handbrake.munki...

The following new items were downloaded:
    /Users/samuel/Library/AutoPkg/Cache/com.github.keeleysam.autopkg.munki.HandBrake/downloads/HandBrake.dmg

The following new items were imported:
    Name                     Version          Catalogs                         Pkginfo Path
    ----                     -------          --------                         ------------
    HandBrake                0.10.1 x86_64    testing                          apps/HandBrake/HandBrake-0.10.1 x86_64.plist
```
