### ISSUE TITLE
Handbrake update has broken the link

### ISSUE THREAD

**Issue by grahampugh** [autopkg/keeleysam-recipes#27]
Hi,

Handbrake has been updated to 0.10.2. The autopkg recipe appears to still be looking for 0.10.1.
New URL is http://handbrake.fr/rotation.php?file=HandBrake-0.10.2-MacOSX.6_GUI_x86_64.dmg

Cheers, Graham

**Comment by keeleysam** [comment]
This uses their sparkle feed which was updated and is working now.
