### ISSUE TITLE
Split munki recipes into download+munki where applicable

### ISSUE THREAD

**Issue by homebysix** [autopkg/keeleysam-recipes#49]
Some of your .munki recipes actually do the work of downloading the app in addition to just importing it into Munki. Would be excellent to have discrete .download recipes to use as the ParentRecipe for your .munki recipe, and this would allow others to create .pkg and other recipes based on the .download as well.

Here's a list of recipes that fit into this category:

- GoogleTalkPlugin/GoogleTalkPlugin.munki.recipe
- Handbrake/Handbrake.munki.recipe
- iTerm2/iTerm2.munki.recipe
- Panic/Coda.munki.recipe
- Panic/Coda2.munki.recipe
- Panic/Transmit.munki.recipe
- Panic/Unison.munki.recipe
- PrimateLabs/Geekbench2.munki.recipe
- PrimateLabs/Wiinote.munki.recipe

Interested? Of course I'd help.

**Comment by keeleysam** [comment]
These recipes were all written before parents existed.  I don't have the
need or any of these changes as I only use Munki, but would accept a pull
request which properly made them.

On Fri, Oct 2, 2015 at 1:57 AM, Elliot Jordan <notifications@github.com>
wrote:

> Some of your .munki recipes actually do the work of downloading the app in
> addition to just importing it into Munki. Would be excellent to have
> discrete .download recipes to use as the ParentRecipe for your .munki
> recipe, and this would allow others to create .pkg and other recipes based
> on the .download as well.
>
> Here's a list of recipes that fit into this category:
>
>    - GoogleTalkPlugin/GoogleTalkPlugin.munki.recipe
>    - Handbrake/Handbrake.munki.recipe
>    - iTerm2/iTerm2.munki.recipe
>    - Panic/Coda.munki.recipe
>    - Panic/Coda2.munki.recipe
>    - Panic/Transmit.munki.recipe
>    - Panic/Unison.munki.recipe
>    - PrimateLabs/Geekbench2.munki.recipe
>    - PrimateLabs/Wiinote.munki.recipe
>
> Interested? Of course I'd help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autopkg/keeleysam-recipes/issues/49>.
>



-- 
Samuel Keeley
