### ISSUE TITLE
Bartender fails to download

### ISSUE THREAD

**Issue by ahaupt11** [autopkg/keeleysam-recipes#57]
On AutoPkg 0.5.1 and 0.5.2, I get this error when running Bartender's Munki recipe:

The following recipes failed:
    Bartender.munki
        Error in local.munki.Bartender: Processor: SparkleUpdateInfoProvider: Error: Can't open URL https://www.macbartender.com/B2/updates/Appcast.xml

Thanks!

**Comment by AndersTao** [comment]
The recipe is working for me, but the URL is for the v1 release.
Updating an override with the URL for v2 works!

My override https://gist.github.com/AndersTao/a25fddd40201cd5e5eb1

**Comment by weswhet** [comment]
Ping!

**Comment by keeleysam** [comment]
resolved with 8551e81
