### ISSUE TITLE
Carbon Copy Cloner recipe returning 404

### ISSUE THREAD

**Issue by flammable** [autopkg/keeleysam-recipes#73]
Hey Sam -

The recipe for CCC has been working great for CCC 4!  CCC 5 came out a couple of weeks ago, but I couldn't figure out how to modify the recipe to download that instead.  Now, it looks like the recipe is failing to download CCC 4.  I noticed this in my AutoPkg output this morning:

```
local.munki.CarbonCopyCloner
       Error in local.munki.CarbonCopyCloner: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
```

Any chance you (or someone else) would be willing to take a look?  Thanks!

Mike

**Comment by keeleysam** [comment]
@flammable thanks for reporting this, I dug into it a little bit and it looks like this application is no longer using Sparkle and instead using a JSON formatted feed located at https://bombich.com/software/updates/ccc.php?os_major=10&os_minor=13&os_bugfix=0&ccc=5061&beta=0&locale=en.  If you'd like to update the recipe to support this, that'd be appreciated.  It's still a zip file, so it just requires replacing the first part of the download phase.  I didn't see anything else using JSON feeds and this appears to be a little custom so it might warrant a provider.

**Comment by flammable** [comment]
Thanks, Sam.  I think it might be over my head, unfortunately.  I hope someone more talented than me at writing AutoPkg recipes has a need for a CCC 5 recipe!

**Comment by rustymyers** [comment]
Hey @flammable, this should be fixed now!

**Comment by flammable** [comment]
Thanks!
