### ISSUE TITLE
Filezilla 404-ing

### ISSUE THREAD

**Issue by ochsenjoch** [autopkg/keeleysam-recipes#75]
The Filezilla recipe is returning a 404.

I have looked at it and it seems the FileZillaURLProvider.py looks at

http://update.filezilla-project.org/updatecheck.php?platform=i686-apple-darwin9&version=3.0.0&osversion=12

http://update-filezilla.project.org is directly redirecting to filezilla-project.org and no updatecheck.php exists there.

**Comment by aysiu** [comment]
I've put in this as a pull request (using hansen-m's download recipe as a parent recipe):
https://github.com/autopkg/keeleysam-recipes/pull/78

**Comment by cwhits** [comment]
The issue is within the url provider. The `update_url` is what's 404'ing:
http://update.filezilla-project.org/updatecheck.php?platform=i686-apple-darwin9&version=3.0.0&osversion=12

**Comment by blackthroat** [comment]
This appears to be working now since commits https://github.com/autopkg/keeleysam-recipes/commit/eaab643f579be4690f03a4e0e7a1add69fae36bd and https://github.com/autopkg/keeleysam-recipes/commit/598eab043ba66d6e523b775c87757f56b80ab023

Thanks everyone!

**Comment by ochsenjoch** [comment]
Yes, works for me as well. Thanks a lot!
