### ISSUE TITLE
FileZilla.munki recipe failing

### ISSUE THREAD

**Issue by eshirk** [autopkg/keeleysam-recipes#93]
FileZilla.munki is running into CodeSignatureVerifier errors.

**Comment by klou** [comment]
see #48

**Comment by fkick** [comment]
Looks like this is still failing per #92

**Comment by klou** [comment]
It looks like some combination of:
- The FilezillaURLProvider update_url is incorrect
- The FilezillaURLProvider update_url has certificate issues
- something else (descriptive, I know)

In any case, the downloaded FileZilla.tar.bz2 is not a valid tarball, so the Unarchiver can't handle it.  So it's not CodeSignatureVerifier-related, at least.

**Comment by aysiu** [comment]
FileZilla now seems to have a .dmg download at https://filezilla-project.org/download.php?type=client

**Comment by klou** [comment]
Yes, but isn't that the "bundled with ads and other things" version?

**Comment by aysiu** [comment]
Doh! You're right!

**Comment by aysiu** [comment]
I think I found it: https://filezilla-project.org/download.php?show_all=1

**Comment by eshirk** [comment]
That’s where I’ve been getting ‘clean’ downloads after the recipe started failing.


On Sep 20, 2018, at 10:30 AM, aysiu <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I found it: https://filezilla-project.org/download.php?show_all=1

**Comment by aysiu** [comment]
> In any case, the downloaded FileZilla.tar.bz2 is not a valid tarball, so the Unarchiver can't handle it. So it's not CodeSignatureVerifier-related, at least.

I'm trying to get around this with maybe a user agent string in the headers, but it's still downloading a 9 KB file instead of a 10 MB one.

**Comment by klou** [comment]
Well, I'm not sure how the FileZillaURLProvider works - but I suspect that it parses the URL used in the FZ built-in UpdateCheck.  This may have changed -- probably need to do a wireshark parse to find it.  Either way, the current parse returns an invalid response.

**Comment by aysiu** [comment]
I'm trying a sample recipe without even using FileZillaURLProvider—just trying a regular URLTextSearcher and URLDownloader. I'm also even just trying `curl` in a terminal without AutoPkg. Can't get the download the work properly.

**Comment by klou** [comment]
FWIW, the OLD UpdateURL currently referenced in FileZillaURLProvider looks like it has an untrusted certificate.  And the current FileZilla (v3.36+) Update Check contacts a different FQDN over SSL, so I couldn't grab a URL off of it.

**Comment by Firefishy** [comment]
The download URL now checks for `user-agent`. The following works:

`curl -v -H 'Connection: close' -H 'User-Agent: FileZilla 3.25.1' "https://dl1.cdn.filezilla-project.org/FileZilla_3.37.4_macosx-x86.app.tar.bz2" -O`
